更新官方配置

diff --git a/.github/workflows/packaging-openwrt-for-qemu-etc.yml b/.github/workflows/packaging-openwrt-for-qemu-etc.yml
--- a/.github/workflows/packaging-openwrt-for-qemu-etc.yml
+++ b/.github/workflows/packaging-openwrt-for-qemu-etc.yml
@@ -1,53 +1,49 @@
 #=====================================================================================
-# https://github.com/ophub/amlogic-s9xxx-openwrt
-# Description: Build OpenWrt with Image Builder
-# Instructions: https://openwrt.org/docs/guide-user/additional-software/imagebuilder
-# Download options: https://downloads.openwrt.org/releases
+# Description: Packaging OpenWrt for qemu, allwinner, rockchip and amlogic
+# Copyright (C) 2021 https://github.com/unifreq/openwrt_packit
+# Copyright (C) 2021 https://github.com/ophub/flippy-openwrt-actions
 #=====================================================================================
 
-name: Build OpenWrt with ImageBuilder
+name: Packaging OpenWrt for qemu, etc.
 
 on:
   repository_dispatch:
   workflow_dispatch:
     inputs:
       branch:
-        description: "Select the releases branch"
+        description: "Select the source branch"
         required: false
-        default: "22.03.0"
+        default: "lede"
         type: choice
         options:
-          - 22.03.0
-          - 21.02.3
-          - 19.07.10
-          - 18.06.9
+          - lede
+          - official
       openwrt_soc:
-        description: "Select Amlogic SoC"
+        description: "Select device SoC"
         required: false
-        default: "s905x3_s905d_s912"
+        default: "qemu_vplus_beikeyun_l1pro_r68s"
         type: choice
         options:
           - all
-          - s905x3_s905d_s912
-          - a311d
+          - qemu_vplus_beikeyun_l1pro_r68s_s922x_s905x3_s905d
+          - qemu_vplus_beikeyun_l1pro_r68s
+          - qemu
+          - vplus
+          - beikeyun
+          - l1pro
+          - r68s
           - s922x
           - s922x-n2
-          - s922x-reva
           - s905x3
           - s905x2
-          - s905x2-km3
           - s912
-          - s912-m8s
           - s905d
-          - s905d-ki
-          - s905x
-          - s905w
           - s905
-          - s905l3a
+          - diy
       openwrt_kernel:
         description: "Select kernel version"
         required: false
-        default: "5.10.135_5.15.50"
+        default: "5.15.50_5.19.1"
         type: choice
         options:
           - 5.4.210_5.10.135_5.15.50
@@ -63,14 +59,9 @@ on:
         required: false
         default: true
         type: boolean
-      openwrt_size:
-        description: "Set the rootfs size(Unit: MiB)."
-        required: false
-        default: "960"
 
 env:
   TZ: America/New_York
-  IMAGEBUILDER_SH: router-config/openwrt-imagebuilder/imagebuilder.sh
 
 jobs:
   build:
@@ -94,40 +85,40 @@ jobs:
           sudo timedatectl set-timezone "${TZ}"
           echo "::set-output name=status::success"
 
-      - name: Build Rootfs with Image Builder
-        id: imagebuilder
-        if: (!cancelled())
+      - name: Download armvirt file
+        id: download
         run: |
-          RELEASES_BRANCH="${{ github.event.inputs.branch }}"
-          chmod +x ${IMAGEBUILDER_SH}
-          ${IMAGEBUILDER_SH} ${RELEASES_BRANCH}
-          echo "RELEASES_BRANCH=${RELEASES_BRANCH}" >> $GITHUB_ENV
+          openwrt_url="$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "OpenWrt_.*${{ github.event.inputs.branch }}.*/.*rootfs.tar.gz" | head -n 1)"
+          [[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found!" && exit 1
+          #
+          armvirt_tarfile_path="openwrt/bin/targets/armvirt/64"
+          [[ -d "${armvirt_tarfile_path}" ]] || mkdir -p ${armvirt_tarfile_path}
+          #
+          wget -q -P "${armvirt_tarfile_path}" "https://github.com/${GITHUB_REPOSITORY}/releases/download/${openwrt_url}"
+          [[ "${?}" -ne "0" ]] && echo "The armvirt file download failed!" && exit 1
           echo "::set-output name=status::success"
 
-      - name: Build OpenWrt firmware
-        if: steps.imagebuilder.outputs.status == 'success' && !cancelled()
-        uses: ophub/amlogic-s9xxx-openwrt@main
-        with:
-          openwrt_path: openwrt/bin/targets/*/*/*rootfs.tar.gz
-          openwrt_soc: ${{ github.event.inputs.openwrt_soc }}
-          openwrt_kernel: ${{ github.event.inputs.openwrt_kernel }}
-          auto_kernel: ${{ github.event.inputs.auto_kernel }}
-          openwrt_size: ${{ github.event.inputs.openwrt_size }}
+      - name: Packaging OpenWrt
+        uses: ophub/flippy-openwrt-actions@main
+        if: steps.download.outputs.status == 'success' && !cancelled()
+        env:
+          OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*rootfs.tar.gz
+          KERNEL_REPO_URL: https://github.com/ophub/kernel/tree/main/pub/stable
+          PACKAGE_SOC: ${{ github.event.inputs.openwrt_soc }}
+          KERNEL_VERSION_NAME: ${{ github.event.inputs.openwrt_kernel }}
+          KERNEL_AUTO_LATEST: ${{ github.event.inputs.auto_kernel }}
 
       - name: Upload OpenWrt Firmware to Release
         uses: ncipollo/release-action@main
         if: env.PACKAGED_STATUS == 'success' && !cancelled()
         with:
-          tag: OpenWrt_Aml_imagebuilder_${{ env.RELEASES_BRANCH }}_${{ env.PACKAGED_OUTPUTDATE }}
+          tag: OpenWrt_aarch64_${{ env.PACKAGED_OUTPUTDATE }}
           artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
           allowUpdates: true
           token: ${{ secrets.GH_TOKEN }}
           body: |
-            This is OpenWrt firmware for Amlogic s9xxx tv box
+            This is OpenWrt firmware for Armvirt 64
             * Firmware information
             Default IP: 192.168.1.1
             Default username: root
             Default password: password
-            Default WIFI name: OpenWrt
-            Default WIFI password: none
-            Install to EMMC: Login to OpenWrt → System → Amlogic Service → Install OpenWrt
diff --git a/.github/workflows/use-releases-file-to-packaging.yml b/.github/workflows/use-releases-file-to-packaging.yml
--- a/.github/workflows/use-releases-file-to-packaging.yml
+++ b/.github/workflows/use-releases-file-to-packaging.yml
@@ -1,8 +1,7 @@
-#========================================================================================================================
+#=====================================================================================
 # https://github.com/ophub/amlogic-s9xxx-openwrt
 # Description: Use Releases file to packaging
-# Cron: min (0 - 59) / hour (0 - 23) / day of month (1 - 31) / month (1 - 12) / day of week (0 - 6)(Sunday - Saturday)
-#========================================================================================================================
+#=====================================================================================
 
 name: Use Releases file to Packaging
 
@@ -11,7 +10,7 @@ on:
   workflow_dispatch:
     inputs:
       branch:
-        description: "Select the packaged source branch"
+        description: "Select the source branch"
         required: false
         default: "lede"
         type: choice
@@ -19,7 +18,7 @@ on:
           - lede
           - official
       openwrt_soc:
-        description: "Select Amlogic SoC"
+        description: "Select device SoC"
         required: false
         default: "all"
         type: choice
@@ -44,16 +43,17 @@ on:
       openwrt_kernel:
         description: "Select kernel version"
         required: false
-        default: "5.10.125_5.15.50"
+        default: "5.10.135_5.15.50"
         type: choice
         options:
-          - 5.4.200_5.10.125
-          - 5.10.125_5.15.50
-          - 5.15.45_5.18.5
-          - 5.4.200
-          - 5.10.125
+          - 5.4.210_5.10.135_5.15.50
+          - 5.4.210_5.10.135
+          - 5.10.135_5.15.50
+          - 5.15.50_5.19.1
+          - 5.4.210
+          - 5.10.135
           - 5.15.50
-          - 5.18.5
+          - 5.19.1
       auto_kernel:
         description: "Auto use the latest kernel"
         required: false
@@ -74,9 +74,10 @@ jobs:
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
       - name: Initialization environment
+        id: init
         env:
           DEBIAN_FRONTEND: noninteractive
         run: |
@@ -85,25 +86,21 @@ jobs:
           sudo -E apt-get -qq install $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt)
           sudo -E apt-get -qq autoremove --purge
           sudo -E apt-get -qq clean
-          sudo timedatectl set-timezone "$TZ"
-          # Input value validation
-          ARR_BRANCH=("official" "lede")
-          if [[ -n "${{ github.event.inputs.branch }}" && -n "$(echo "${ARR_BRANCH[@]}" | grep -w "${{ github.event.inputs.branch }}")" ]]; then
-            RELEASES_BRANCH=${{ github.event.inputs.branch }}
-          else
-            RELEASES_BRANCH=lede
-          fi
-          echo "RELEASES_BRANCH=${RELEASES_BRANCH}" >> $GITHUB_ENV
-          echo "COMPILE_STARTINGTIME=$(date +"%m.%d.%H%M")" >> $GITHUB_ENV
+          sudo timedatectl set-timezone "${TZ}"
+          echo "::set-output name=status::success"
 
       - name: Download OpenWrt Armvirt firmware
         id: down
         if: (!cancelled())
         run: |
+          openwrt_url="$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "OpenWrt_.*${{ github.event.inputs.branch }}.*/.*rootfs.tar.gz" | head -n 1)"
+          [[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found!" && exit 1
+          #
           armvirt_tarfile_path="openwrt/bin/targets/armvirt/64"
-          [ -d "${armvirt_tarfile_path}" ] || mkdir -p ${armvirt_tarfile_path}
-          curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "openwrt_s9xxx_${{ env.RELEASES_BRANCH }}.*/.*rootfs.tar.gz" | head -n 1 > DOWNLOAD_ARMVIRT
-          [ -s DOWNLOAD_ARMVIRT ] && wget -q -P ${armvirt_tarfile_path} https://github.com/${GITHUB_REPOSITORY}/releases/download/$(cat DOWNLOAD_ARMVIRT)
+          [[ -d "${armvirt_tarfile_path}" ]] || mkdir -p ${armvirt_tarfile_path}
+          #
+          wget -q -P "${armvirt_tarfile_path}" "https://github.com/${GITHUB_REPOSITORY}/releases/download/${openwrt_url}"
+          [[ "${?}" -ne "0" ]] && echo "The armvirt file download failed!" && exit 1
           echo "::set-output name=status::success"
 
       - name: Build OpenWrt firmware
@@ -120,7 +117,7 @@ jobs:
         uses: ncipollo/release-action@main
         if: env.PACKAGED_STATUS == 'success' && !cancelled()
         with:
-          tag: openwrt_s9xxx_${{ env.RELEASES_BRANCH }}_${{ env.PACKAGED_OUTPUTDATE }}
+          tag: OpenWrt_Aml_${{ github.event.inputs.branch }}_${{ env.PACKAGED_OUTPUTDATE }}
           artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
           allowUpdates: true
           token: ${{ secrets.GH_TOKEN }}
